### ISSUE TITLE
Error when deploying basic stack

### ISSUE THREAD

**Issue by ferdinandsalis** [theserverlessway/aws-account-setup#1]
When I try to deploy the basic setup I get the following error,

> 2018-07-22 10:38:21 UTC+0000   CREATE_FAILED              AWS::IAM::Role                   LambdaRole                       Action vendors (e.g., aws, ec2, etc.) must not
                                                                                                                            contain wildcards. (Service:
                                                                                                                            AmazonIdentityManagement; Status Code: 400; Error
                                                                                                                            Code: MalformedPolicyDocument

**Comment by flomotlik** [comment]
Oh sorry I somehow missed this Issue. I updated the upstream template from Widdix: https://github.com/widdix/aws-cf-templates/blob/master/security/account-password-policy.yaml

This should work fine now.
